### PR TITLE
Fix for #100 - timestamp migrations do not work in MariaDB

### LINKED ISSUE #100: timestamp migrations do not work in MariaDB
```yaml
   Customer:
      description: customer is the one that orders a campaign
      type: object
      required:
        - id
        - name
        - created_at

      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 100

        created_at:
          type: string
          format: datetime
          nullable: false
          x-db-type: datetime
          default: CURRENT_TIMESTAMP
        updated_at:
          type: string
          format: datetime
          default: null
          nullable: true
          x-db-type: datetime
```

generates a migration:

```php
class m220524_140002_change_table_customers extends \yii\db\Migration
{
    public function up()
    {
        $this->alterColumn('{{%customers}}', 'created_at', $this->timestamp()->notNull()->defaultExpression("CURRENT_TIMESTAMP"));
    }

    public function down()
    {
        $this->alterColumn('{{%customers}}', 'created_at', $this->timestamp()->notNull()->defaultExpression("CURRENT_TIMESTAMP"));
    }
}
```

### PR DESCRIPTION
**Pull request by SOHELAHMED7**
Fix #100 

---

This PR is continued from https://github.com/cebe/yii2-openapi/pull/103

---

**This PR will:**

 - [x] change all tests to use real DB inside Docker container. All tests should run in container. Running tests outside container may fail it. Also it will avoid mocks in tests as we require separate migration code for different databases
 - [x] change Github Action workflow to run all tests in container
 - [x] implement `x-db-type` and will fix bugs related to it
 - [ ] solve issue related  to timestamp/datetime in Mariadb (and possibly in MySQL). Corresponding behaviour in Pgsql is fine and should not be affected
 - [x] add `defaultValue()` tests for text, json, blob, geometry for Mysql, Mariadb and Pgsql. In general make default value implementation perfect and add tests for it.
 - [x] by default run all tests in MySQL DB
 - [x] remove all `enum` and `json` related tests partially or completely to focus on above tasks. It will be added later in their own PR. See #111 and #109 . This tests are removed to focus on solution for above tasks. Also `enum` and `json` implementation needs to re-check as it produce errors
 - [x] ensure all changes by @siggi-k on [!112](https://github.com/cebe/yii2-openapi/pull/103) works fine in all DB: Mysql, Mariadb, Pgsql

---

#### Sub-tasks

 - [x] remove `uuid` tests from Mariadb and Mysql as it is only supported in PgSQL
 - [x] use real DB and real Yii app in tests instead of mocks
 - [x] add tests to check `down()` code in migrations for `x-db-type` in fresh and secondary code generation of migrations
 - [ ] refactor tests and dataprovider in tests/unit/MigrationsGeneratorTest.php
 - [x] run all tests in Github actions inside Docker container
 - [x] implement `x-db-type` works perfectly in Mariadb, Mysql and Pgsql
 - [x] fix erroneous tests in Github actions
 - [x] fix/adjust failing tests
 - [x] Github actions: run all tests in containers in GA
 - [x] support for data type with array e.g. `text[]` (in `x-db-type`)
 - [x] as there are lot of tests are changed, add lot of tests for `x-db-type`, timestamp/datetime issue, enum, object issues and these all for all DBs: Pgsql, Mysql, Maridb
 - [x] add `defaultValue()` tests for text, json, blob, geometry for Mysql, Mariadb and Pgsql
 - [x] Mariadb (and possibly Mysql) timestamp issue in generated migrations issue in `up()` and `down()` code
 - [x] resolve PR review comments from the maintainer 
 - [x] "double precision precision" issue in `alterColumn()`

---

 -  ~~enum datatype in yaml issue in Mariadb; also check this issue is reproduced in Mysql~~ see #111 
 -  ~~object datatype in yaml issue in Mariadb; also check this issue is reproduced in Mysql~~ see #109

### CODE REVIEW

**Comment by SOHELAHMED7** [comment]
TODO

 - [ ] remove `uuid` tests from Mariadb and Mysql as it is only supported in PgSQL
 - [ ] implement `x-db-type` works perfectly in Mariadb, Mysql and Pgsql
 - [ ] fix/adjust failing tests

Later

 - [ ] Mariadb timestamp in generated migrations issue
 - [ ] enum datatype in yaml issue in Mariadb; also check this issue is reproduced in Mysql
 - [ ] object datatype in yaml issue in Mariadb; also check this issue is reproduced in Mysql

File: src/lib/ColumnToCode.php [hunk 1]
```diff
@@ -227,14 +273,37 @@ private function resolve():void
...
             $this->rawParts['type'] =
                 $this->column->dbType . (strpos($this->column->dbType, '(') !== false ? '' : $rawSize);
         }
+        
+        $this->isBuiltinType = $this->getIsBuiltinType($type, $dbType);
+
         $this->resolveDefaultValue();
     }
 
+    /**
```
Comment (cebe) [inline src/lib/ColumnToCode.php:290]: please add a description what "builtin type" means.
also add a comment that explains why this returns false for the combination of enum and mariadb.

Comment (SOHELAHMED7) [reply src/lib/ColumnToCode.php:345]: I have added docs for what builtInType means. But for the return false part for enum and Mariadb, I am not able to figure out completely. Possibly enum does not have its corresponding method in \yii\db\SchemaBuilderTrait. And I think for all DB enum should return `false`. Also this is added by @siggi-k , at this moment I don't have concrete reason. I will look at this again when I take issue #111 in hand

**Review by cebe — APPROVED** [review]
Great work, thank you very much!

I will test this branch in some projects and see if I find any issues with it. If not I'll merge it.

**Comment by SOHELAHMED7** [comment]
I found a issue that is introduced by this PR. It is 'decimal' in x-db-type is detected as string in models and faker generation. It is being fixed in https://github.com/SOHELAHMED7/yii2-openapi/pull/2

**Comment by SOHELAHMED7** [comment]
> I found a issue that is introduced by this PR. It is 'decimal' in x-db-type is detected as string in models and faker generation. It is being fixed in https://github.com/SOHELAHMED7/yii2-openapi/pull/2


fixed in https://github.com/SOHELAHMED7/yii2-openapi/pull/2/commits/3d4d71c6cee2dddba8ace4496b38ef07f0fe8475

Also this introduce some minor changes in models generation

'float' will be now 'double' due to compatibility with [gettype](https://www.php.net/gettype) function of PHP

e.g.

```diff

-  * @property float $amount amount
+ * @property double $amount amount

```

File: src/lib/migrations/BaseMigrationBuilder.php [hunk 2]
```diff
@@ -411,4 +419,31 @@ protected function isNeedUsingExpression(string $fromType, string $toType):bool
...
+
+        Yii::$app->db->createCommand('DROP TABLE IF EXISTS '.$tableName)->execute();
+
+        if (is_string($columnSchema->xDbType) && !empty($columnSchema->xDbType)) {
+            $column = [$columnSchema->name.' '.$this->newColStr($columnSchema)];
+        } else {
+            $column = [$columnSchema->name => $this->newColStr($columnSchema)];
+        }
+
+        Yii::$app->db->createCommand()->createTable($tableName, $column)->execute();
```
Comment (cebe) [inline src/lib/migrations/BaseMigrationBuilder.php:435]: This breaks for me with the following error:

```
Exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'
The SQL being executed was: CREATE TABLE `tmp_table_` (
	created_at datetime NOT NULL DEFAULT 'CURRENT_TIMESTAMP'
)'

in /app/vendor/yiisoft/yii2/db/Schema.php:676

Error Info:
Array
(
    [0] => 42000
    [1] => 1067
    [2] => Invalid default value for 'created_at'
)

Caused by: Exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at''

in /app/vendor/yiisoft/yii2/db/Command.php:1302

Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('CREATE TABLE `t...')
#2 /app/vendor/cebe/yii2-openapi/src/lib/migrations/BaseMigrationBuilder.php(435): yii\db\Command->execute()
#3 /app/vendor/cebe/yii2-openapi/src/lib/migrations/MysqlMigrationBuilder.php(48): cebe\yii2openapi\lib\migrations\BaseMigrationBuilder->tmpSaveNewCol(Object(cebe\yii2openapi\db\ColumnSchema))
#4 /app/vendor/cebe/yii2-openapi/src/lib/migrations/BaseMigrationBuilder.php(214): cebe\yii2openapi\lib\migrations\MysqlMigrationBuilder->compareColumns(Object(yii\db\mysql\ColumnSchema), Object(cebe\yii2openapi\db\ColumnSchema))
#5 /app/vendor/cebe/yii2-openapi/src/lib/migrations/BaseMigrationBuilder.php(71): cebe\yii2openapi\lib\migrations\BaseMigrationBuilder->buildSecondary()
#6 /app/vendor/cebe/yii2-openapi/src/lib/generators/MigrationsGenerator.php(114): cebe\yii2openapi\lib\migrations\BaseMigrationBuilder->build()
#7 /app/vendor/cebe/yii2-openapi/src/lib/generators/MigrationsGenerator.php(74): cebe\yii2openapi\lib\generators\MigrationsGenerator->buildMigrations()
#8 /app/vendor/cebe/yii2-openapi/src/generator/ApiGenerator.php(485): cebe\yii2openapi\lib\generators\MigrationsGenerator->generate()
#9 /app/vendor/yiisoft/yii2-gii/src/console/GenerateAction.php(53): cebe\yii2openapi\generator\ApiGenerator->generate()
#10 /app/vendor/yiisoft/yii2-gii/src/console/GenerateAction.php(36): yii\gii\console\GenerateAction->generateCode()
#11 [internal function]: yii\gii\console\GenerateAction->run()
#12 /app/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#13 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#14 /app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('api', Array)
#15 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('api', Array)
#16 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('gii/api', Array)
#17 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('gii/api', Array)
#18 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 /app/yii(31): yii\base\Application->run()
#20 {main}
```

column specification is this one:

```
        created_at:
          readOnly: true
          type: string
          format: datetime
          x-db-type: datetime
          nullable: false
```

DB: MariaDB

Comment (SOHELAHMED7) [reply src/lib/migrations/BaseMigrationBuilder.php:435]:
```diff
- default: CURRENT_TIMESTAMP
+ default: current_timestamp()  
```

**Comment by cebe** [comment]
Found a few more things (tested on the `timestamp-enum-x-db-type-bug-fix` branch):

- [ ] Definition in schema: 
       
```yaml
       billing_type:
          type: string
          description: |
            Billing type:
            - CPM - Cost per 1000 sends
            - CPL - Cost per Lead
            - CPO - Cost per Order
            - CPC - Cost per Click
          maxLength: 3
          enum:
            - CPM
            - CPL
            - CPO
            - CPC
```

results in the following migration (quotes are note escaped):

```php
        $this->alterColumn('{{%campaigns}}', 'billing_type', 'enum('CPM', 'CPL', 'CPO', 'CPC') NULL DEFAULT NULL');
```

image

**Comment by SOHELAHMED7** [comment]
For above comment; fix is already applied. Present in https://github.com/SOHELAHMED7/yii2-openapi/pull/2/files

File: src/lib/AttributeResolver.php [hunk 3]
```diff
@@ -203,6 +203,8 @@ protected function resolveProperty(PropertySchema $property, bool $isRequired):v
                   ->setDescription($property->getAttr('description', ''))
                   ->setReadOnly($property->isReadonly())
                   ->setDefault($property->guessDefault())
+                  ->setXDbType($property->getAttr('x-db-type'))
+                  ->setNullable($property->getProperty()->getSerializableData()->nullable ?? null)
```
Comment (cebe) [inline src/lib/AttributeResolver.php:207]: why do you call `getSerializableData()` here? nullable should be accessable directly on the object. `getSerializableData()` is a significant performance overhead.

```suggestion
                  ->setNullable($property->getProperty()->nullable ?? null)
```

**Review by cebe — CHANGES_REQUESTED** [review]

File: src/lib/AttributeResolver.php (hunk 3 above)
Comment (SOHELAHMED7) [reply src/lib/AttributeResolver.php:207]: That line is added by @siggi-k . Putting your suggested changes breaks few tests. I am checking this problem

Comment (SOHELAHMED7) [reply src/lib/AttributeResolver.php:207]: I think that solution by @siggi-k by using `getSerializableData()` is only correct way if we want to set nullable as described in [README docs](https://github.com/SOHELAHMED7/yii2-openapi/tree/100-timestamp-migrations-do-not-work-in-mariadb#handling-of-not-null-constraints) because [default value handling of nullable by OpenAPI spec](https://github.com/cebe/php-openapi/blob/master/src/spec/Schema.php#L127-L130) is somewhat different than what we want in the yii2-openapi lib

Comment (cebe) [reply src/lib/AttributeResolver.php:207]: I see, thanks for checking that. This is making the generator significantly slower on layer5, I'd like to check other ways to get the original value of nullable.

Comment (cebe) [reply src/lib/AttributeResolver.php:207]: Created another issue to handle this separately https://github.com/cebe/yii2-openapi/issues/123

**Comment by cebe** [comment]
Thank you!
