### PR TITLE
Fix-xDbType

### LINKED ISSUE #99: Attribute does not respect `nullable` or type null

### LINKED ISSUE #100: timestamp migrations do not work in MariaDB
```yaml
   Customer:
      description: customer is the one that orders a campaign
      type: object
      required:
        - id
        - name
        - created_at

      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 100

        created_at:
          type: string
          format: datetime
          nullable: false
          x-db-type: datetime
          default: CURRENT_TIMESTAMP
        updated_at:
          type: string
          format: datetime
          default: null
          nullable: true
          x-db-type: datetime
```

generates a migration:

```php
class m220524_140002_change_table_customers extends \yii\db\Migration
{
    public function up()
    {
        $this->alterColumn('{{%customers}}', 'created_at', $this->timestamp()->notNull()->defaultExpression("CURRENT_TIMESTAMP"));
    }

    public function down()
    {
        $this->alterColumn('{{%customers}}', 'created_at', $this->timestamp()->notNull()->defaultExpression("CURRENT_TIMESTAMP"));
    }
}
```

### PR DESCRIPTION
**Pull request by siggi-k**
**x-db-type** will no longer be reformatted from now on.
**x-db-type** is now the final entry in db.

nullalble property is handled correctly.

usecase
```
created_at:
  readOnly: true
  type: string
  format: datetime
  x-db-type: datetime
  nullable: false
```

fixes #100 
fixes #99

### CODE REVIEW

File: src/lib/items/Attribute.php [hunk 1]
```diff
@@ -117,6 +122,17 @@ public function setDbType(string $dbType):Attribute
...
+    public function setXDbType($xDbType):Attribute
+    {
+        $this->xDbType = $xDbType;
+        return $this;
+    }
+
+    public function getXDbType($xDbType)
+    {
+        return $this->xDbType;
+    }
```
Comment (cebe) [inline src/lib/items/Attribute.php:134]: Getter is not required here.

**Review by cebe — CHANGES_REQUESTED** [review]

**Comment by cebe** [comment]
Tests are failing after these changes.

File: src/lib/ColumnToCode.php [hunk 2]
```diff
@@ -314,10 +327,18 @@ private function resolveDefaultValue():void
...
-        if ($type === 'tsvector') {
-            return false;
+        switch ($type){
+            case 'tsvector':
+                return false;
+            case 'blob':
+            case 'geometry':
+            case 'text':
+            case 'json':
+                return ($this->isMysql() && !$this->isMariaDb()) === false;
```
Comment (cebe) [inline src/lib/ColumnToCode.php:337]: condition looks hard to read, should be positive check instead of negative.

**Comment by SOHELAHMED7** [comment]
Completing this PR in https://github.com/cebe/yii2-openapi/pull/112

File: src/lib/ColumnToCode.php (hunk 2 above)
Comment (SOHELAHMED7) [reply src/lib/ColumnToCode.php:392]: Condition:

It was like this before: (refactored in this PR to use switch-case)

```php
return !($this->isMysql() && !$this->isMariaDb() && in_array($type, ['blob', 'geometry', 'text', 'json']));
```

  | is mysql | is mariadb | type in array | final | global negation
-- | -- | -- | -- | -- | --
mysql json | T | !F=T | T | T | F
mysql nonjson | T | !F=T | F | F | T
mariadb json | F | !T=F | T | F | T
mariadb nonjson | F | !T=F | F | F | T

---

Default are not allowed for  BLOB, TEXT, GEOMETRY, and JSON in MySQL [prior to MySQL 8.0.13](https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html)

Curious to know why it is allowed for MariaDB?

Comment (cebe) [reply src/lib/ColumnToCode.php:392]: mariadb allows default value for JSON column at least, have been using that a few times. e.g. `data JSON NOT NULL DEFAULT '{}'`
